/**
 * Step two of signing in: the emailed code.
 *
 * Note what the design and the server disagree about. The design says
 * "generated by your authenticator application"; the server emails a
 * six-digit code and tells you which address it went to. The copy here
 * follows the server, because that is what the person is actually looking
 * at, and shows the masked hint it returns.
 *
 * Expired, already used and too-many-attempts all come back as the same 400,
 * deliberately not saying which — so the way out is "start again", not "try
 * another code".
 */

import { ShieldAlert } from 'lucide-react'
import { useState } from 'react'
import { Alert, OtpInput } from '@/components'
import type { ApiError } from '@/api/errors'
import type { LoginChallenge } from '@/api/types'

const CODE_LENGTH = 6

interface VerifyCodeCardProps {
  challenge?: LoginChallenge | null
  onSubmit: (code: string) => void
  onRestart: () => void
  pending: boolean
  error: ApiError | null
}

export function VerifyCodeCard({
  challenge,
  onSubmit,
  onRestart,
  pending,
  error,
}: VerifyCodeCardProps) {
  const [code, setCode] = useState('')
  const complete = code.length === CODE_LENGTH

  return (
    <div className="auth-card">
      <div className="auth-card__halo">
        <ShieldAlert size={26} strokeWidth={2} aria-hidden />
      </div>

      <h1 className="auth-card__title">Two-Factor Authentication</h1>

      <p className="auth-card__body">
        {challenge?.email_hint
          ? `Enter the ${CODE_LENGTH}-digit code we emailed to ${challenge.email_hint}.`
          : 'Enter the 6-digit verification code generated by your authenticator application.'}
      </p>

      {error && <Alert tone="error">{error.message}</Alert>}

      <OtpInput
        value={code}
        onChange={setCode}
        onComplete={onSubmit}
        length={CODE_LENGTH}
        disabled={pending}
        invalid={Boolean(error)}
      />

      <button
        type="button"
        className="auth-card__verify-btn"
        disabled={!complete || pending}
        onClick={() => onSubmit(code)}
      >
        {pending ? 'Verifying…' : 'Verify & Sign In'}
      </button>

      <div className="auth-card__links">
        <button
          type="button"
          className="auth-card__back-link"
          onClick={onRestart}
        >
          Back to Login
        </button>
      </div>
    </div>
  )
}
