/**
 * Step two of signing in: the emailed code.
 *
 * Note what the design and the server disagree about. The design says
 * "generated by your authenticator application"; the server emails a
 * six-digit code and tells you which address it went to. The copy here
 * follows the server, because that is what the person is actually looking
 * at, and shows the masked hint it returns.
 *
 * Expired, already used and too-many-attempts all come back as the same 400,
 * deliberately not saying which — so the way out is "start again", not "try
 * another code".
 */

import { ShieldAlert } from 'lucide-react'
import { useState } from 'react'
import { Alert, Button, OtpInput } from '@/components'
import type { ApiError } from '@/api/errors'
import type { LoginChallenge } from '@/api/types'

const CODE_LENGTH = 6

interface VerifyCodeCardProps {
  challenge: LoginChallenge
  onSubmit: (code: string) => void
  onRestart: () => void
  pending: boolean
  error: ApiError | null
}

export function VerifyCodeCard({
  challenge,
  onSubmit,
  onRestart,
  pending,
  error,
}: VerifyCodeCardProps) {
  const [code, setCode] = useState('')
  const complete = code.length === CODE_LENGTH

  return (
    <div className="auth-card">
      <div className="auth-card__halo">
        <ShieldAlert size={30} aria-hidden />
      </div>

      <h1 className="auth-card__title">Two-Factor Authentication</h1>

      <p className="auth-card__body">
        Enter the {CODE_LENGTH}-digit code we emailed to{' '}
        <strong>{challenge.email_hint}</strong>.
      </p>

      {error && <Alert tone="error">{error.message}</Alert>}

      <OtpInput
        value={code}
        onChange={setCode}
        onComplete={onSubmit}
        length={CODE_LENGTH}
        disabled={pending}
        invalid={Boolean(error)}
      />

      <Button size="lg" disabled={!complete || pending} onClick={() => onSubmit(code)}>
        {pending ? 'Verifying…' : 'Verify & Sign In'}
      </Button>

      <div className="auth-card__links">
        <button type="button" className="link-quiet link-button" onClick={onRestart}>
          Back to Login
        </button>
      </div>
    </div>
  )
}
